//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdlib.h>
#include <stdio.h>
#include <limits.h>

#define fibLimit 4000000

int main(int argc, char const *argv[])
{
	unsigned int a0=1,a1=2, a2=0;
	unsigned long Sum=0;
	while (a1<fibLimit)
	{
		if (a1%2==0)  Sum+=a1;
		a2 = a0 + a1;
		a0=a1;
		a1=a2;
		printf("%d, ",a2);
	}
	printf("Sum = %ld\n", Sum); 
	return 0;
}

